project_id = "uogenwcycqykfsuongrl"

[functions.auth-register]
verify_jwt = false

[functions.auth-verify-email]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-logout]
verify_jwt = false

[functions.auth-session]
verify_jwt = false

[functions.auth-send-email]
verify_jwt = false

[functions.mobile-api]
verify_jwt = false

[functions.web-api]
verify_jwt = false

[functions.process-recording]
verify_jwt = false

[functions.session-maintenance]
verify_jwt = false

[functions.cleanup-recordings]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.google-maps-key]
verify_jwt = false

[functions.google-maps-key-public]
verify_jwt = false

[functions.copom-outbound-call]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.auth-setup-password]
verify_jwt = false

[functions.auth-request-reset]
verify_jwt = false

[functions.admin-audio-auto]
verify_jwt = false

[functions.support-api]
verify_jwt = false

[functions.seed-recordings-timeline]
verify_jwt = false
