project_id = "uogenwcycqykfsuongrl"

[functions.auth-register]
verify_jwt = false

[functions.auth-verify-email]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-logout]
verify_jwt = false

[functions.auth-session]
verify_jwt = false

[functions.auth-send-email]
verify_jwt = false

[functions.mobile-api]
verify_jwt = false
